version: 0.1
component: build
timeoutInSeconds: 6000
runAs: root
shell: bash
env:
  vaultVariables: null
  exportedVariables:
    - BUILD_ID
steps:
  - type: Command
    name: Export variables
    timeoutInSeconds: 40
    command: |
      export BUILD_ID=`echo ${OCI_BUILD_RUN_ID} | rev | cut -c 1-7`
      echo "BUILD_ID: " $BUILD_ID
    onFailure:
      - type: Command
        timeoutInSeconds: 40
        command: |
          echo "Handling Failure"
          echo "Failure successfully handled"
        runAs: root
  - type: Command
    name: 'Install NVM, Node, NPM, Yarn'
    timeoutInSeconds: 400
    command: >
      wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh
      | bash

      source .bashrc

      nvm install v14.18.1

      npm install --global yarn
  - type: Command
    timeoutInSeconds: 1200
    name: Build container image
    command: |
      cd ${OCI_WORKSPACE_DIR}/frontend-service
      docker build --pull --rm -t frontend-service .
    onFailure:
      - type: Command
        command: |
          echo "Handling Failure"
          echo "Failure successfully handled"
        timeoutInSeconds: 40
        runAs: root
outputArtifacts:
  - name: output01
    type: DOCKER_IMAGE
    location: 'frontend-service:latest'
  - name: output02
    type: BINARY
    location: ${OCI_WORKSPACE_DIR}/frontend-service/deploy/frontend-service-deployment.yaml

