apiVersion: apps/v1
kind: Deployment
metadata: 
  name: frontend-app
  namespace: acme
  labels:
    app: frontend
spec: 
  selector: 
    matchLabels: 
      app: frontend
  replicas: 1
  template: 
    metadata: 
      labels: 
        app: frontend 
    spec: 
      containers: 
        - name: frontend
          image: fra.ocir.io/apaccpt03/acme/frontend-service:${BUILD_ID}              	  
          imagePullPolicy: Always
          ports: 
            - name: http
              containerPort: 9080
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 200m
      imagePullSecrets:
        - name: ocirsecret
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: acme
spec:
  selector:
    app: frontend
  ports:
    - port: 4200
      protocol: TCP
      targetPort: 4200
      name: http
  type: ClusterIP
#---
#apiVersion: networking.k8s.io/v1
#kind: Ingress
#metadata:
#  name: frontend-ingress
#  namespace: acme
#  annotations:
#    kubernetes.io/ingress.class: "nginx"
#    cert-manager.io/cluster-issuer: "acme-application-letsencrypt-prod"
#    certmanager.k8s.io/acme-challenge-type: "http01"
#spec:
#  tls:
#  - hosts:
#    - acme.pov.ocloud.today
#    secretName: acme-prod-certificate-secret
#  rules:
#  -   host: acme.pov.ocloud.today
#      http:
#        paths:
#        - path: /
#          pathType: Prefix
#          backend:
#            service:
#              name: frontend-service
#              port:
#                number: 80